"""
HTML Content Generation Agent

This agent detects when slide content needs HTML visualization
and generates appropriate HTML content for timelines, process flows,
charts, and other custom visualizations.
"""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, List, Optional

from langchain_core.runnables import RunnableConfig

from .agents import SlideGenerationState
from .html_renderer import HTMLRenderer
from .llm_client import LangchainLLMClient, SlideContent
from .monitoring import monitor_agent_execution


class HTMLContentGenerationAgent:
    """
    Agent responsible for detecting and generating HTML visualizations
    for slide content that requires custom graphics or interactive elements
    """

    def __init__(self):
        self.name = "html_content_generator"
        self.llm_client = LangchainLLMClient()

        # Initialize HTML renderer with error handling
        try:
            self.html_renderer = HTMLRenderer()
            self.html_available = True
            print(f"✅ {self.name}: HTML renderer initialized successfully")
        except RuntimeError as e:
            print(f"⚠️ {self.name}: HTML renderer not available: {e}")
            self.html_available = False

        # Setup debug folder for HTML files
        self.debug_folder = Path("html_debug")
        self.debug_enabled = os.getenv("HTML_DEBUG", "true").lower() == "true"

        if self.debug_enabled:
            self.debug_folder.mkdir(exist_ok=True)
            print(
                f"🔍 {self.name}: HTML debug mode enabled - "
                f"files saved to {self.debug_folder}"
            )

    @monitor_agent_execution("html_content_generator")
    def execute(
        self, state: SlideGenerationState, config: Optional[RunnableConfig] = None
    ) -> SlideGenerationState:
        """
        Convert descriptive content for HTML slides into actual HTML visualizations.

        This agent takes the descriptive content generated by the content generation
        phase and transforms it into actual HTML code for visualization-designated slides.

        Args:
            state: Current workflow state with generated slide contents and
                   presentation plan
            config: Langchain configuration with callbacks

        Returns:
            Updated state with HTML visualizations processed
        """
        print(
            f"🎨 {self.name}: Converting descriptive content to HTML visualizations..."
        )

        try:
            # Check prerequisites
            slide_contents = state.get("slide_contents")
            presentation_plan = state.get("presentation_plan")

            if not slide_contents or not presentation_plan:
                print(f"⚠️ {self.name}: Missing slide contents or presentation plan")
                return state

            if not self.html_available:
                print(f"⚠️ {self.name}: HTML rendering not available, skipping...")
                return state

            # Process slides using the presentation plan's HTML flags
            processed_slides = self._process_planned_html_slides(
                slide_contents, presentation_plan, state.get("topic", ""), config
            )

            # Update state with processed content
            state["slide_contents"] = processed_slides
            state["current_step"] = "html_content_generation_complete"

            html_count = sum(
                1
                for slide in processed_slides
                for content in slide.content.values()
                if self._is_html_visualization(content)
            )

            print(f"✅ {self.name}: Processed {len(processed_slides)} slides")
            print(
                f"✅ {self.name}: Converted {html_count} descriptions to HTML visualizations"
            )

            return state

        except Exception as e:
            print(f"❌ {self.name}: Error during HTML content generation: {e}")
            # Don't fail the workflow - HTML generation is optional
            state["current_step"] = "html_content_generation_complete"
            return state

    def _process_slides_for_html_content(
        self,
        slide_contents: List[SlideContent],
        topic: str,
        config: Optional[RunnableConfig] = None,
    ) -> List[SlideContent]:
        """
        Process all slides to detect and enhance content with HTML visualizations

        Args:
            slide_contents: List of slide content objects
            topic: Presentation topic for context
            config: Langchain configuration

        Returns:
            List of processed slide content with HTML visualizations
        """
        processed_slides = []
        html_generated_count = 0

        print(f"  🔍 Analyzing {len(slide_contents)} slides for HTML opportunities...")

        for i, slide_content in enumerate(slide_contents, 1):
            print(f"  📄 Processing slide {i} (Layout {slide_content.layout_index})...")

            # Show what placeholders this slide has
            placeholder_names = list(slide_content.content.keys())
            print(f"      Placeholders: {placeholder_names}")

            # Analyze content for HTML visualization opportunities
            enhanced_content = self._enhance_slide_with_html_content(
                slide_content, topic, i, len(slide_contents), config
            )

            # Check if HTML was generated for this slide
            html_generated_for_slide = any(
                self._is_html_visualization(content)
                for content in enhanced_content.content.values()
            )

            if html_generated_for_slide:
                html_generated_count += 1
                print(f"      ✅ HTML visualization generated for slide {i}")
            else:
                print(f"      ⚪ No HTML visualization for slide {i}")

            processed_slides.append(enhanced_content)

        print("  📊 HTML Generation Summary:")
        print(f"      Total slides: {len(slide_contents)}")
        print(f"      HTML visualizations: {html_generated_count}")
        print(f"      Coverage: {html_generated_count}/{len(slide_contents)} slides")

        return processed_slides

    def _enhance_slide_with_html_content(
        self,
        slide_content: SlideContent,
        topic: str,
        slide_number: int,
        total_slides: int,
        config: Optional[RunnableConfig] = None,
    ) -> SlideContent:
        """
        Enhance a single slide with HTML visualizations where appropriate

        Args:
            slide_content: Original slide content
            topic: Presentation topic
            slide_number: Current slide number
            total_slides: Total slides in presentation
            config: Langchain configuration

        Returns:
            Enhanced slide content with HTML visualizations
        """
        enhanced_content = {}
        html_generated_this_slide = False

        for placeholder_name, content_text in slide_content.content.items():
            print(f"        📝 Checking '{placeholder_name}'...")
            print(f"           Content preview: {content_text[:100]}...")

            # Check if this placeholder should have HTML visualization
            should_generate = self._should_generate_html_visualization(
                placeholder_name, content_text
            )

            if should_generate:
                print(f"        🎨 Generating HTML for '{placeholder_name}'")

                # Generate enhanced HTML content (without detailed specifications)
                html_content = self._generate_html_visualization_content(
                    placeholder_name=placeholder_name,
                    original_content=content_text,
                    topic=topic,
                    slide_number=slide_number,
                    total_slides=total_slides,
                    slide_spec=None,
                    config=config,
                )

                if html_content:
                    enhanced_content[placeholder_name] = html_content
                    html_generated_this_slide = True
                    print(f"        ✅ Generated HTML for '{placeholder_name}'")
                else:
                    # Keep original content if HTML generation fails
                    enhanced_content[placeholder_name] = content_text
                    print("        ⚠️  HTML generation failed, keeping original")
            else:
                # Keep original content for non-HTML placeholders
                enhanced_content[placeholder_name] = content_text
                print(f"        ⚪ Keeping original content for '{placeholder_name}'")

        if not html_generated_this_slide:
            print("        💡 No HTML content generated for this slide")
            print("           Consider using visualization keywords in content")
            print("           (timeline, process, workflow, steps, comparison, etc.)")

        return SlideContent(
            layout_index=slide_content.layout_index, content=enhanced_content
        )

    def _process_planned_html_slides(
        self,
        slide_contents: List[SlideContent],
        presentation_plan: List[Any],  # List[SlideSpec]
        topic: str,
        config: Optional[RunnableConfig] = None,
    ) -> List[SlideContent]:
        """
        Convert descriptive content to HTML visualizations for slides marked as HTML

        This method identifies slides planned for HTML visualization and converts
        their descriptive content into actual HTML code.

        Args:
            slide_contents: List of slide content objects with descriptive content
            presentation_plan: List of SlideSpec objects with is_html flags
            topic: Presentation topic for context
            config: Langchain configuration

        Returns:
            List of processed slide content with HTML visualizations where planned
        """
        processed_slides = []
        html_generated_count = 0

        print(
            f"  🔍 Converting descriptive content for {len(slide_contents)} slides..."
        )

        for i, (slide_content, slide_spec) in enumerate(
            zip(slide_contents, presentation_plan), 1
        ):
            is_html_planned = getattr(slide_spec, "is_html", False)
            layout_info = f"Layout {slide_content.layout_index}"

            if is_html_planned:
                print(f"  📄 Converting HTML slide {i} ({layout_info})...")
            else:
                print(f"  📄 Skipping non-HTML slide {i} ({layout_info})...")

            # Show what placeholders this slide has
            placeholder_names = list(slide_content.content.keys())
            print(f"      Placeholders: {placeholder_names}")

            if is_html_planned:
                # Convert descriptive content to HTML for slides planned as HTML
                enhanced_content = self._enhance_planned_html_slide(
                    slide_content, slide_spec, topic, i, len(slide_contents), config
                )

                # Check if HTML was actually generated for this slide
                html_generated_for_slide = any(
                    self._is_html_visualization(content)
                    for content in enhanced_content.content.values()
                )

                if html_generated_for_slide:
                    html_generated_count += 1
                    print(f"      ✅ HTML visualization generated for slide {i}")
                else:
                    print(f"      ⚠️ HTML generation failed for planned HTML slide {i}")

                processed_slides.append(enhanced_content)
            else:
                # Keep non-HTML slides as-is
                processed_slides.append(slide_content)
                print(f"      ⚪ Kept standard content for slide {i}")

        print("  📊 HTML Conversion Summary:")
        print(f"      Total slides: {len(slide_contents)}")
        html_planned = sum(
            1 for spec in presentation_plan if getattr(spec, "is_html", False)
        )
        print(f"      HTML planned: {html_planned}")
        print(f"      HTML generated: {html_generated_count}")
        print(
            f"      Success rate: {html_generated_count}/{html_planned} "
            "planned HTML slides converted"
        )

        return processed_slides

    def _enhance_planned_html_slide(
        self,
        slide_content: SlideContent,
        slide_spec: Any,  # SlideSpec
        topic: str,
        slide_number: int,
        total_slides: int,
        config: Optional[RunnableConfig] = None,
    ) -> SlideContent:
        """
        Enhance a single slide that is planned to be HTML with HTML visualizations

        Args:
            slide_content: Original slide content
            slide_spec: The SlideSpec object for this slide
            topic: Presentation topic
            slide_number: Current slide number
            total_slides: Total slides in presentation
            config: Langchain configuration

        Returns:
            Enhanced slide content with HTML visualizations
        """
        enhanced_content = {}
        html_generated_this_slide = False

        for placeholder_name, content_text in slide_content.content.items():
            print(f"        📝 Checking '{placeholder_name}'...")
            print(f"           Content preview: {content_text[:100]}...")

            # Check if this placeholder should have HTML visualization
            should_generate = self._should_generate_html_visualization(
                placeholder_name, content_text
            )

            if should_generate:
                print(f"        🎨 Generating HTML for '{placeholder_name}'")

                # Generate enhanced HTML content with detailed specifications
                html_content = self._generate_html_visualization_content(
                    placeholder_name=placeholder_name,
                    original_content=content_text,
                    topic=topic,
                    slide_number=slide_number,
                    total_slides=total_slides,
                    slide_spec=slide_spec,
                    config=config,
                )

                if html_content:
                    enhanced_content[placeholder_name] = html_content
                    html_generated_this_slide = True
                    print(f"        ✅ Generated HTML for '{placeholder_name}'")
                else:
                    # Keep original content if HTML generation fails
                    enhanced_content[placeholder_name] = content_text
                    print("        ⚠️  HTML generation failed, keeping original")
            else:
                # Keep original content for non-HTML placeholders
                enhanced_content[placeholder_name] = content_text
                print(f"        ⚪ Keeping original content for '{placeholder_name}'")

        if not html_generated_this_slide:
            print("        💡 No HTML content generated for this slide")
            print("           Consider using visualization keywords in content")
            print("           (timeline, process, workflow, steps, comparison, etc.)")

        return SlideContent(
            layout_index=slide_content.layout_index, content=enhanced_content
        )

    def _should_generate_html_visualization(
        self, placeholder_name: str, content_text: str
    ) -> bool:
        """
        Determine if a placeholder should have HTML visualization

        Args:
            placeholder_name: Name of the placeholder
            content_text: Current content text

        Returns:
            True if HTML visualization should be generated
        """
        placeholder_lower = placeholder_name.lower()
        content_lower = content_text.lower()

        # Skip icon placeholders - they have specific icon handling
        is_icon_placeholder = "icon" in placeholder_lower
        if is_icon_placeholder:
            return False

        # ✅ EXPANDED DETECTION LOGIC:

        # 1. HTML-specific placeholders (Layout 3)
        is_html_placeholder = any(
            keyword in placeholder_lower
            for keyword in ["html", "picture from html", "picture generated from html"]
        )

        # 2. Picture/image placeholders (original logic)
        is_picture_placeholder = any(
            keyword in placeholder_lower
            for keyword in ["picture", "image", "visual", "graphic", "diagram"]
        )

        # 3. Chart placeholders that could be HTML charts
        is_chart_placeholder = any(
            keyword in placeholder_lower
            for keyword in ["chart", "graph", "data visualization", "metrics"]
        )

        # 4. Content placeholders with visualization-worthy content
        is_content_placeholder = any(
            keyword in placeholder_lower
            for keyword in ["content", "text content", "main content", "body"]
        )

        # Check content for visualization keywords
        visualization_keywords = [
            "timeline",
            "process",
            "workflow",
            "steps",
            "phases",
            "stages",
            "journey",
            "roadmap",
            "comparison",
            "vs",
            "versus",
            "before and after",
            "chart",
            "graph",
            "data",
            "metrics",
            "statistics",
            "flowchart",
            "diagram",
            "visualization",
            "infographic",
            "development process",
            "project phases",
            "methodology",
        ]

        has_visualization_keywords = any(
            keyword in content_lower for keyword in visualization_keywords
        )

        # Detect structured content that could benefit from visualization
        has_multiple_items = (
            content_text.count("\n") >= 2 or content_text.count(",") >= 2
        )
        has_dates = any(
            date_indicator in content_lower
            for date_indicator in [
                "2024",
                "2025",
                "q1",
                "q2",
                "q3",
                "q4",
                "january",
                "february",
                "march",
                "april",
                "may",
                "june",
                "july",
                "august",
                "september",
                "october",
                "november",
                "december",
            ]
        )
        has_sequential_content = any(
            seq_indicator in content_lower
            for seq_indicator in [
                "first",
                "then",
                "next",
                "finally",
                "step",
                "phase",
                "stage",
                "1.",
                "2.",
                "3.",
                "•",
                "-",
            ]
        )

        # DECISION LOGIC:

        # Always generate for HTML-specific placeholders
        if is_html_placeholder:
            print(f"    🎯 HTML placeholder detected: '{placeholder_name}'")
            return True

        # Generate for picture/chart placeholders with visualization content
        if (
            is_picture_placeholder or is_chart_placeholder
        ) and has_visualization_keywords:
            print(f"    🎯 Visual placeholder with viz content: '{placeholder_name}'")
            return True

        # Generate for content placeholders with strong visualization indicators
        if is_content_placeholder and (
            has_visualization_keywords
            or (has_multiple_items and has_dates)
            or (has_multiple_items and has_sequential_content)
        ):
            print(
                f"    🎯 Content placeholder with structured data: '{placeholder_name}'"
            )
            return True

        return False

    def _generate_html_visualization_content(
        self,
        placeholder_name: str,
        original_content: str,
        topic: str,
        slide_number: int,
        total_slides: int,
        slide_spec: Optional[Any] = None,
        config: Optional[RunnableConfig] = None,
    ) -> Optional[str]:
        """
        Generate HTML visualization content for a specific placeholder

        Args:
            placeholder_name: Name of the placeholder to generate content for
            original_content: Original text content from the placeholder
            topic: Overall presentation topic
            slide_number: Current slide number
            total_slides: Total number of slides

        Returns:
            HTML content string or None if generation failed
        """
        try:
            prompt = self._create_html_generation_prompt(
                placeholder_name,
                original_content,
                topic,
                slide_number,
                total_slides,
                slide_spec,
            )

            # Generate HTML content
            generated_html = self.llm_client.generate_content(
                system_prompt=self._get_html_generation_system_prompt(),
                user_prompt=prompt,
                config=config,
            )

            if not generated_html:
                print("        ⚠️ No HTML content generated")
                return original_content

            # Clean the response
            cleaned_html = self._clean_llm_response(generated_html)

            # Validate and correct Lucide icon names in HTML
            validated_html = self._validate_and_correct_html_icons(cleaned_html, topic)

            # Fix common Mermaid syntax issues
            fixed_html = self._fix_mermaid_syntax(validated_html)

            # Ensure proper HTML structure for script injection
            complete_html = self._ensure_complete_html_structure(fixed_html)

            # Debug: Show what was generated (summary)
            if complete_html:
                print(f"    🔍 Generated {len(complete_html)} chars of content")

            if complete_html and self._validate_html_content(complete_html):
                # Save HTML to debug folder if enabled
                if self.debug_enabled and complete_html:
                    self._save_html_debug_file(
                        complete_html,
                        placeholder_name,
                        topic,
                        slide_number,
                        original_content,
                    )

                return complete_html

            # Fallback: Try to create basic HTML wrapper if content looks like HTML
            if cleaned_html and ("<" in cleaned_html and ">" in cleaned_html):
                print(f"    🔧 Wrapping partial HTML content for '{placeholder_name}'")
                wrapped_html = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .timeline {{ color: #dc261e; }}
    </style>
</head>
<body>
    {cleaned_html}
</body>
</html>"""
                if self._validate_html_content(wrapped_html):
                    # Save wrapped HTML to debug folder
                    if self.debug_enabled:
                        self._save_html_debug_file(
                            wrapped_html,
                            placeholder_name,
                            topic,
                            slide_number,
                            original_content,
                            suffix="_wrapped",
                        )
                    return wrapped_html

            print(f"    ⚠️ Generated content not valid HTML for '{placeholder_name}'")
            if cleaned_html:
                print(f"    🔍 Generated content was: {cleaned_html[:500]}...")
            return None

        except Exception as e:
            print(f"    ❌ Error generating HTML content: {e}")
            return None

    def _clean_llm_response(self, content: str) -> str:
        """
        Clean LLM response to remove markdown formatting and other artifacts

        Args:
            content: Raw LLM response content

        Returns:
            Cleaned HTML content
        """
        if not content:
            return content

        # Remove leading/trailing whitespace
        content = content.strip()

        # Remove markdown code block markers
        if content.startswith("```html"):
            content = content[7:]  # Remove ```html
        elif content.startswith("```"):
            content = content[3:]  # Remove ```

        if content.endswith("```"):
            content = content[:-3]  # Remove trailing ```

        # Remove any remaining leading/trailing whitespace
        content = content.strip()

        # Remove any triple quotes if they appear
        if content.startswith("'''html"):
            content = content[7:]
        elif content.startswith("'''"):
            content = content[3:]

        if content.endswith("'''"):
            content = content[:-3]

        return content.strip()

    def _create_html_generation_prompt(
        self,
        placeholder_name: str,
        original_content: str,
        topic: str,
        slide_number: int,
        total_slides: int,
        slide_spec: Optional[Any] = None,
    ) -> str:
        """Create prompt for HTML visualization generation."""

        # Build context section
        context_section = f"""
CONTEXT:
- Presentation Topic: {topic}
- Slide you are working on from the full deck: {slide_number} of {total_slides}
- Placeholder: {placeholder_name}
- Original Content: {original_content}"""

        # Add detailed specs if available
        if slide_spec:
            specs = []
            if hasattr(slide_spec, "detailed_purpose") and slide_spec.detailed_purpose:
                specs.append(f"- Detailed Purpose: {slide_spec.detailed_purpose}")
            if (
                hasattr(slide_spec, "content_structure")
                and slide_spec.content_structure
            ):
                specs.append(f"- Content Structure: {slide_spec.content_structure}")
            if (
                hasattr(slide_spec, "html_requirements")
                and slide_spec.html_requirements
            ):
                specs.append(f"- HTML Requirements: {slide_spec.html_requirements}")
            if hasattr(slide_spec, "visual_elements") and slide_spec.visual_elements:
                specs.append(f"- Visual Elements: {slide_spec.visual_elements}")
            if hasattr(slide_spec, "key_information") and slide_spec.key_information:
                key_info = ", ".join(slide_spec.key_information)
                specs.append(f"- Key Information: {key_info}")

            if specs:
                context_section += "\n\nDETAILED SLIDE SPECIFICATIONS:\n"
                context_section += "\n".join(specs)
                context_section += (
                    "\n\nCRITICAL: Your HTML visualization MUST implement "
                    "these specifications exactly."
                )

        # Static requirements section
        requirements_section = """
VIEWPORT REQUIREMENTS:
1.  **Overall Container**: The `<body>` of the HTML MUST be exactly `1577x603` pixels. Use Tailwind classes `w-[1577px] h-[603px]`. The root element should be a flex container (`flex`, `w-full`, `h-full`) to manage layout.

2.  **Diagram Sizing**: The `div` containing a Mermaid diagram should NOT fill the entire container if there is other content (like a title or descriptive text).
    - Use flexbox or grid to allocate space. For example, a title can be in one `div` and the diagram in another `div` that takes the remaining space (`flex-grow`).
    - The diagram's container should have padding (e.g., `p-8`) to ensure it doesn't touch the edges.
    - Example Layout:
      <body class="w-[1577px] h-[603px] flex flex-col p-8">
        <h1 class="text-3xl font-bold mb-4">Diagram Title</h1>
        <div class="mermaid flex-grow">
          ... Mermaid diagram ...
        </div>
      </body>

3.  **No Overflow**: All content, including text and the diagram, MUST fit within the `1577x603` viewport without any scrolling or content being cut off.
"""

        # Visual design section
        design_section = """
VISUAL DESIGN (CRITICAL):
- Color Palette:
  - Primary/Accent: Swiss Red (#dc261e)
  - Text (Headings): Dark Grey (#2d3748)
  - Text (Body): Black (#000000)
  - Background: White (#ffffff)

- Typography:
  - Font: 'Segoe UI', system-ui, sans-serif
  - Base Size: 16px (text-base)
  - Headers: 24px (text-2xl, font-bold)

- Layout:
  - Keep it clean, simple, and minimalist.
  - Use ample white space.
  - Ensure content is highly readable.

- Components:
  - Use DaisyUI and Flowbite components for layout and elements.
  - Use Mermaid.js for diagrams, molecular pathways, etc.
  - Repurpose components creatively (e.g., an Event Schedule can be used for a sequence of steps).
  - Use Tailwind CSS for custom styling and adjustments."""

        # Example section
        example_section = """
COMPONENT EXAMPLES:
Use these proven patterns for building your visualization.

1. DaisyUI Stats for Metrics:
<div class="stats shadow">
  <div class="stat">
    <div class="stat-title">Customer Satisfaction</div>
    <div class="stat-value text-primary">95%</div>
    <div class="stat-desc">↗︎ 400 (22%)</div>
  </div>
  <div class="stat">
    <div class="stat-title">Projects Completed</div>
    <div class="stat-value text-primary">200+</div>
    <div class="stat-desc">↗︎ 90 (14%)</div>
  </div>
</div>

2. DaisyUI Cards for Comparisons:
<div class="grid grid-cols-2 gap-4">
  <div class="card bg-base-100 shadow-sm">
    <div class="card-body">
      <h2 class="card-title">Before</h2>
      <p>Manual processes, 2-week deployment</p>
    </div>
  </div>
  <div class="card bg-base-100 shadow-sm">
    <div class="card-body">
      <h2 class="card-title">After</h2>
      <p>Automated pipeline, 2-hour deployment</p>
    </div>
  </div>
</div>

3. Mermaid Timeline:
<div class="mermaid">
timeline
    title Project Phases
    2024-01 : Discovery : Requirements
    2024-02 : Development : Core Build
    2024-03 : Testing : QA Process
    2024-04 : Launch : Go Live
</div>

4. Mermaid Process Flow:
<div class="mermaid">
flowchart TD
    A[Requirements] --> B[Design]
    B --> C[Development]
    C --> D{Testing}
    D -->|Pass| E[Deploy]
    D -->|Fail| C
</div>

5. Mermaid Graph with Subgraphs (CORRECT SYNTAX):
<div class="mermaid">
graph TD
    subgraph "Phase 1"
        A[Planning]
        B[Requirements]
    end
    subgraph "Phase 2"
        C[Development]
        D[Testing]
    end
    A --> B
    B --> C
    C --> D
</div>

6. Mermaid Cycle Diagram (SAFE SYNTAX):
<div class="mermaid">
flowchart TD
    A[Start Process] --> B[Action 1]
    B --> C[Action 2]
    C --> D[Action 3]
    D --> E[End Result]
    E --> B
    style A fill:#f3f4f6
    style E fill:#dc261e,color:#fff
</div>

7. Stats with Lucide Icons:
<div class="stat">
  <div class="stat-figure text-primary">
    <svg class="w-8 h-8"><use href="#trending-up"></use></svg>
  </div>
  <div class="stat-title">Revenue Growth</div>
  <div class="stat-value">31%</div>
</div>

8. Card with Mermaid Diagram:
<div class="card bg-base-100 shadow-sm">
  <div class="card-body">
    <h2 class="card-title">Development Process</h2>
    <div class="mermaid">
    flowchart TD
        A[Requirements] --> B[Design]
        B --> C[Code]
        C --> D[Test]
    </div>
  </div>
</div>

9. Side-by-Side Comparison with Diagrams:
<div class="grid grid-cols-2 gap-4">
  <div class="card bg-base-100 shadow-sm">
    <div class="card-body">
      <h2 class="card-title">Before</h2>
      <p>Manual deployment process</p>
      <div class="mermaid">
      flowchart TD
          A[Code] --> B[Manual Test]
          B --> C[Manual Deploy]
      </div>
    </div>
  </div>
  <div class="card bg-base-100 shadow-sm">
    <div class="card-body">
      <h2 class="card-title">After</h2>
      <p>Automated CI/CD pipeline</p>
      <div class="mermaid">
      flowchart TD
          A[Code] --> B[Auto Test]
          B --> C[Auto Deploy]
      </div>
    </div>
  </div>
</div>

10. Complex Layout with Multiple Components:
<div class="w-full h-full p-8">
  <h1 class="text-2xl font-bold mb-4">Project Overview</h1>
  <div class="mermaid mb-6">
  timeline
      title Project Timeline
      2024-01 : Planning : Requirements
      2024-02 : Development : Core Features
      2024-03 : Testing : QA Process
  </div>
  <div class="stats shadow w-full">
    <div class="stat">
      <div class="stat-figure text-primary">
        <svg class="w-8 h-8"><use href="#users"></use></svg>
      </div>
      <div class="stat-title">Team Size</div>
      <div class="stat-value">8</div>
    </div>
    <div class="stat">
      <div class="stat-figure text-primary">
        <svg class="w-8 h-8"><use href="#calendar"></use></svg>
      </div>
      <div class="stat-title">Duration</div>
      <div class="stat-value">3 months</div>
    </div>
  </div>
</div>"""

        # Combine all sections
        return "\n\n".join(
            [
                (
                    "Convert descriptive content into HTML visualization for a PowerPoint slide "
                    "placeholder."
                ),
                context_section,
                requirements_section,
                design_section,
                example_section,
                (
                    "CONVERSION TASK:\n"
                    "The original content contains descriptions of what should be visualized. "
                    "Your job is to convert these descriptions into functional HTML code that "
                    "creates the described visualization.\n\n"
                    "OUTPUT:\nReturn ONLY the complete HTML code. "
                    "No explanations or markdown."
                ),
            ]
        )

    def _get_html_generation_system_prompt(self) -> str:
        """Get system prompt for HTML generation"""
        return """You are an expert web developer and data visualization specialist.
Your mission is to convert descriptive content into visually compelling HTML 
visualizations that perfectly fill a 1577x603px container for business presentations.

**Your Role:** You receive descriptive content about what should be visualized 
(timelines, processes, comparisons, etc.) and convert it into functional HTML code.

**Core Principles:**
1.  **Content Conversion**: Transform descriptions into actual visualizations
2.  **Strict Component Usage**: Your ONLY tools for layout and components
    are DaisyUI and Flowbite. You MUST NOT use any other library or write
    custom components.
3.  **Brand Consistency**: Strictly adhere to the specified color palette.
    Use Tailwind CSS to override component styles if necessary to match the theme.
    - Primary/Accent: Swiss Red (#dc261e)
    - Text: Dark Grey for headers (#2d3748), Black for body (#000000)
    - Background: White (#ffffff)
4.  **Static & Non-Interactive**: The output is for a static image.
    DO NOT include animations, hover effects, or any user interactivity.
5.  **No Custom SVG**: You MUST NOT generate any inline SVG code. The ONLY
    way to use icons is with the Lucide icon sprite system, like:
    `<svg><use href="#icon-name"></use></svg>`.

**Layout and Sizing (CRITICAL):**
- The **ENTIRE HTML `<body>`** is the `1577x603px` container.
- If the content includes a diagram AND other elements (like a title), you MUST divide the space.
- The Mermaid diagram `div` must be smaller than the body to leave room for titles, text, etc.
- Use Flexbox or Grid to create a balanced layout. For example:
  - A heading at the top.
  - A `flex-grow` container below it for the diagram, with padding (`p-8`).
- **NEVER** make the diagram's container `w-full h-full` if other content exists.

**Rendering Optimization (CRITICAL):**
- For visualizations, use fixed pixel values (px) instead of percentages for critical positioning
- Use high z-index values (z-30, z-40, z-50) to ensure proper layering
- For leader lines and connectors, use specific pixel values and avoid percentage-based positioning
- Add multiple font fallbacks to ensure text displays correctly in all rendering environments
- For complex layouts with multiple sections, use CSS grid instead of flex with percentage widths
- For labels and annotations, use fixed positioning with absolute pixel values rather than relative positioning
- When creating diagrams:
  - Use fixed pixel values for all positioning (left: 200px instead of left: 50%)
  - Place leader lines with specific coordinates (top: 300px, left: 400px)
  - Ensure text has high contrast against backgrounds
  - Use z-index values of at least 30 for important elements
  - Specify font-family with multiple fallbacks: font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;

**Mermaid.js Best Practices (PREVENT FAILURES):**
- NEVER use HTML tags like <b>, <i>, <br/> inside Mermaid node text
- Always use quotes around node text: A["Simple Text"] not A[Simple Text]
- For line breaks in node text, use \\n instead of <br/>
- Keep node text simple and short (under 30 characters per line)
- Use consistent arrow types: --> (solid), -.-> (dotted), ==> (thick)
- Start diagrams with proper declarations: flowchart TD, graph TD, timeline
- Avoid complex styling within Mermaid - let the renderer handle colors
- Test syntax: each diagram must have valid start declaration and proper node connections
- For subgraphs, use quotes: subgraph "Title" not subgraph Title

**Library Usage Guidelines:**
1.  **DaisyUI & Flowbite**: Use for ALL UI components (cards, stats, badges, buttons, etc.).
    Available DaisyUI components: stats, card, badge, alert, timeline (CSS-only), progress
    Available Flowbite components: timeline, cards, tables, lists
    Stick to simple, clean components that work well in static images.

2.  **Mermaid.js for ALL Diagrams**: For ANY chart, graph, process flow,
    timeline, organizational chart, or diagram, you MUST use Mermaid.js syntax.
    - Timeline: Use `timeline` syntax for chronological sequences
    - Process: Use `flowchart TD` or `graph TD` for workflows  
    - Comparison: Use `graph LR` for side-by-side comparisons
    - Organizational: Use `graph TD` for hierarchies and structures
    - Place ALL Mermaid syntax inside a `<div class="mermaid">` element
    - The renderer automatically applies Ekona brand colors, do not add styling
    - Keep diagrams simple enough to fit within 1577x603px container
    - Follow the examples provided below for proven syntax patterns
    - **CRITICAL MERMAID SYNTAX RULES**:
      * Use simple text in nodes, avoid HTML tags like <b>, <br/>, <i>
      * Use quotes for node text: A["Simple Text Here"]
      * For line breaks in text, use \\n instead of <br/>
      * Avoid complex styling - let the renderer handle colors
      * Test syntax: ensure proper flowchart/graph declarations
      * Use consistent arrow types: --> (solid), -.-> (dotted), ==> (thick)

3.  **POWERFUL COMBINATION - Components + Diagrams**: 
    You can place Mermaid diagrams INSIDE DaisyUI/Flowbite components for rich visualizations:
    - Cards with diagrams: Perfect for comparisons, process explanations
    - Stats with mini diagrams: Add visual context to metrics
    - Complex layouts: Combine timelines, cards, stats, and diagrams creatively
    - The HTML renderer automatically handles Mermaid.js injection regardless of nesting

4.  **Lucide Icons ONLY**: Use existing Lucide icons from the sprite system.
    - Reference via: `<svg class="w-6 h-6"><use href="#icon-name"></use></svg>`
    - Common available icons: trending-up, trending-down, users, clock, 
      dollar-sign, check, x, arrow-right, calendar, star, heart, etc.
    - DO NOT create custom icons or use icon libraries other than Lucide
    - DO NOT generate inline SVG code - only use the sprite system

5.  **NO Custom Graphics**: 
    - Do not create custom SVG illustrations
    - Do not use external image URLs (they won't render)
    - Do not create complex custom graphics or animations
    - Stick to text, Mermaid diagrams, DaisyUI components, and Lucide icons

Your HTML must be production-ready, clean, and convert the provided descriptive 
content into compelling visual presentations for PowerPoint slides.
"""

    def _validate_html_content(self, content: str) -> bool:
        """
        Validate that content is proper HTML

        Args:
            content: Content string to validate

        Returns:
            True if content appears to be valid HTML
        """
        content_lower = content.lower().strip()

        # Check for basic HTML structure
        has_doctype = "<!doctype" in content_lower or "<html" in content_lower
        has_body = "<body" in content_lower

        # Check for common HTML elements
        has_elements = any(
            tag in content_lower for tag in ["<div", "<p", "<h1", "<h2", "<h3", "<span"]
        )

        # Relaxed validation - if it has HTML structure, accept it
        has_basic_html = "<" in content and ">" in content

        # Validate Mermaid syntax if present
        if '<div class="mermaid">' in content:
            mermaid_valid = self._validate_mermaid_syntax(content)
            if not mermaid_valid:
                print("    ⚠️ Invalid Mermaid syntax detected")
                return False

        # Accept if it has proper structure OR basic HTML tags
        return (has_doctype and has_body and has_elements) or (
            has_doctype and has_basic_html
        )

    def _validate_mermaid_syntax(self, html_content: str) -> bool:
        """
        Validate Mermaid diagram syntax in HTML content

        Args:
            html_content: HTML content containing Mermaid diagrams

        Returns:
            True if Mermaid syntax is valid
        """
        import re

        try:
            # Extract Mermaid diagram content
            mermaid_pattern = r'<div class="mermaid">(.*?)</div>'
            mermaid_matches = re.findall(mermaid_pattern, html_content, re.DOTALL)

            if not mermaid_matches:
                return True  # No Mermaid diagrams to validate

            for diagram_content in mermaid_matches:
                diagram_content = diagram_content.strip()

                # Common Mermaid syntax issues that cause failures
                issues = []

                # Check for HTML tags in nodes (common cause of failures)
                if re.search(r"<[^>]+>", diagram_content):
                    issues.append("HTML tags found in Mermaid nodes")

                # Check for proper diagram type declaration
                valid_starts = [
                    "graph",
                    "flowchart",
                    "timeline",
                    "pie",
                    "journey",
                    "gitgraph",
                ]
                first_line = diagram_content.split("\n")[0].strip().lower()
                if not any(first_line.startswith(start) for start in valid_starts):
                    issues.append(f"Invalid diagram type: {first_line}")

                # Check for unmatched quotes
                quote_count = diagram_content.count('"')
                if quote_count % 2 != 0:
                    issues.append("Unmatched quotes in Mermaid syntax")

                # Check for invalid arrow syntax
                invalid_arrows = ["--o>", "<--o", "--->", "<---"]
                for arrow in invalid_arrows:
                    if arrow in diagram_content:
                        issues.append(f"Invalid arrow syntax: {arrow}")

                if issues:
                    print(f"    ⚠️ Mermaid validation issues: {issues}")
                    return False

            return True

        except Exception as e:
            print(f"    ⚠️ Error validating Mermaid syntax: {e}")
            return False

    def _fix_mermaid_syntax(self, html_content: str) -> str:
        """
        Fix common Mermaid syntax issues that cause rendering failures

        Args:
            html_content: HTML content with potentially problematic Mermaid syntax

        Returns:
            HTML content with fixed Mermaid syntax
        """
        import re

        try:
            # Extract and fix each Mermaid diagram
            def fix_mermaid_diagram(match):
                diagram_content = match.group(1).strip()

                # Fix 1: Remove HTML tags and replace with simple text
                diagram_content = re.sub(r"<b>(.*?)</b>", r"\1", diagram_content)
                diagram_content = re.sub(r"<i>(.*?)</i>", r"\1", diagram_content)
                diagram_content = re.sub(r"<br\s*/?>", r"\\n", diagram_content)
                diagram_content = re.sub(r"<[^>]+>", "", diagram_content)

                # Fix 2: Ensure proper quotes around node text
                # Match patterns like A[text] and ensure quotes: A["text"]
                diagram_content = re.sub(
                    r'(\w+)\[([^"\]]+)\]',
                    lambda m: f'{m.group(1)}["{m.group(2).strip()}"]',
                    diagram_content,
                )

                # Fix 3: Replace invalid arrow types
                arrow_fixes = {
                    "--o>": "-->",
                    "<--o": "<--",
                    "--->": "-->",
                    "<---": "<--",
                    "-.o>": "-.->",
                    "=o=>": "==>",
                }
                for old_arrow, new_arrow in arrow_fixes.items():
                    diagram_content = diagram_content.replace(old_arrow, new_arrow)

                # Fix 4: Clean up excessive whitespace
                lines = diagram_content.split("\n")
                cleaned_lines = []
                for line in lines:
                    line = line.strip()
                    if line:  # Skip empty lines
                        cleaned_lines.append(line)

                diagram_content = "\n    ".join(cleaned_lines)

                return f'<div class="mermaid">\n    {diagram_content}\n</div>'

            # Apply fixes to all Mermaid diagrams
            mermaid_pattern = r'<div class="mermaid">(.*?)</div>'
            fixed_content = re.sub(
                mermaid_pattern, fix_mermaid_diagram, html_content, flags=re.DOTALL
            )

            return fixed_content

        except Exception as e:
            print(f"    ⚠️ Error fixing Mermaid syntax: {e}")
            return html_content

    def _is_html_visualization(self, content: str) -> bool:
        """Check if content is an HTML visualization"""
        return self._validate_html_content(content)

    def _save_html_debug_file(
        self,
        html_content: str,
        placeholder_name: str,
        topic: str,
        slide_number: int,
        original_content: str,
        suffix: str = "",
    ) -> None:
        """
        Save HTML content to debug file for comparison and verification

        Args:
            html_content: Generated HTML content
            placeholder_name: Name of the placeholder
            topic: Presentation topic
            slide_number: Slide number
            original_content: Original text content
            suffix: Optional suffix for filename
        """
        if not self.debug_enabled:
            return

        try:
            # Ensure debug directory exists
            os.makedirs(self.debug_folder, exist_ok=True)

            # Create filename with slide info and timestamp
            slide_num = slide_number
            clean_placeholder = "".join(
                c for c in placeholder_name if c.isalnum() or c in ("-", "_")
            )[:30]
            timestamp = datetime.now().strftime("%H%M%S")

            # Note: Lucide sprites are automatically injected by HTMLRenderer during rendering
            # No need to inject here - keep debug files clean and lightweight

            base_filename = (
                f"slide_{slide_num:02d}_{clean_placeholder}_{timestamp}{suffix}"
            )
            html_file = os.path.join(self.debug_folder, f"{base_filename}.html")
            json_file = os.path.join(self.debug_folder, f"{base_filename}.json")

            # Save HTML file with sprite included
            with open(html_file, "w", encoding="utf-8") as f:
                f.write(html_content)

            # Save metadata JSON
            metadata = {
                "timestamp": datetime.now().isoformat(),
                "slide_number": slide_number,
                "placeholder_name": placeholder_name,
                "topic": topic,
                "original_content_length": len(original_content),
                "generated_html_length": len(html_content),
                "lucide_sprite_included": False,  # Sprites are injected during rendering, not in debug files
            }

            with open(json_file, "w", encoding="utf-8") as f:
                json.dump(metadata, f, indent=2)

            print(f"    💾 Saved HTML debug file: {base_filename}.html")

        except Exception as e:
            print(f"    ⚠️ Failed to save debug file: {e}")

    def _validate_and_correct_html_icons(self, html_content: str, topic: str) -> str:
        """
        Validate and correct Lucide icon names in HTML content

        Args:
            html_content: HTML content containing Lucide icon references
            topic: Presentation topic for context in corrections

        Returns:
            HTML content with corrected icon names
        """
        try:
            # Extract icon names from HTML
            import re

            icon_pattern = r'<use href="#([^"]+)"></use>'
            icon_matches = re.findall(icon_pattern, html_content)

            if not icon_matches:
                return html_content

            print(
                f"    🔍 Found {len(icon_matches)} Lucide icons in HTML: {icon_matches}"
            )

            # Get valid Lucide icon names from sprite
            valid_icons = self._get_valid_lucide_icons()

            # Find invalid icons
            invalid_icons = []
            for icon_name in icon_matches:
                if icon_name not in valid_icons:
                    invalid_icons.append(icon_name)

            if not invalid_icons:
                print("    ✅ All Lucide icons are valid")
                return html_content

            print(f"    ⚠️ Invalid Lucide icons: {invalid_icons}")

            # Get corrections from LLM
            corrections = self._get_lucide_icon_corrections(
                invalid_icons, topic, valid_icons
            )

            if not corrections:
                print("    ⚠️ No corrections generated")
                return html_content

            print(f"    ✅ Generated corrections: {corrections}")

            # Apply corrections to HTML
            corrected_html = html_content
            for invalid_icon, valid_icon in corrections.items():
                old_ref = f'<use href="#{invalid_icon}"></use>'
                new_ref = f'<use href="#{valid_icon}"></use>'
                corrected_html = corrected_html.replace(old_ref, new_ref)
                print(f"    📝 Corrected '{invalid_icon}' → '{valid_icon}' in HTML")

            return corrected_html

        except Exception as e:
            print(f"    ⚠️ Error validating HTML icons: {e}")
            return html_content

    def _get_valid_lucide_icons(self) -> list:
        """Get list of valid Lucide icon names from the sprite"""
        try:
            if not self.html_renderer or not self.html_renderer.lucide_sprite_content:
                return []

            # Extract icon IDs from sprite content
            import re

            id_pattern = r'id="([^"]+)"'
            valid_icons = re.findall(
                id_pattern, self.html_renderer.lucide_sprite_content
            )
            return valid_icons

        except Exception as e:
            print(f"Warning: Could not extract Lucide icons: {e}")
            return []

    def _get_lucide_icon_corrections(
        self, invalid_icons: list, topic: str, valid_icons: list
    ) -> dict:
        """
        Get corrections for invalid Lucide icon names using LLM

        Args:
            invalid_icons: List of invalid icon names
            topic: Presentation topic for context
            valid_icons: List of all valid Lucide icon names

        Returns:
            Dictionary mapping invalid icons to corrected icons
        """
        try:
            # Sample valid icons for prompt (first 100 alphabetically)
            sample_valid_icons = sorted(valid_icons)[:100]

            prompt = (
                f"""
The following Lucide icon names are INVALID and need correction:
{', '.join(invalid_icons)}

Presentation topic: {topic}

AVAILABLE LUCIDE ICONS (sample of {len(sample_valid_icons)} """
                + f"""from {len(valid_icons)} total):
{', '.join(sample_valid_icons)}

For each invalid icon, suggest the closest valid Lucide icon name that:
1. ✅ EXISTS in the Lucide library (from the list above)
2. 🎯 Has similar meaning/purpose to the invalid icon
3. 📝 Fits the presentation topic: "{topic}"
4. 🔤 Uses exact Lucide naming (hyphen-separated, lowercase)

Common corrections:
- check-circle -> circle-check
- edit -> pen or pencil
- bar-chart -> bar-chart-3
- money -> coins

Please respond in this EXACT format:
invalid_icon1 -> valid_icon1
invalid_icon2 -> valid_icon2
"""
            )

            system_prompt = """You are an expert Lucide icon validation specialist.
Your task is to correct invalid Lucide icon names to valid alternatives.

CRITICAL REQUIREMENTS:
- ONLY suggest icon names from the provided valid icons list
- Choose icons with similar semantic meaning
- Use exact Lucide naming conventions (lowercase, hyphen-separated)
- Consider the presentation context when choosing alternatives"""

            # Use the LLM client to generate corrections
            response = self.llm_client.generate_content(
                system_prompt=system_prompt, user_prompt=prompt
            )

            if not response:
                return {}

            # Parse corrections from response
            corrections = {}
            lines = response.strip().split("\n")

            for line in lines:
                if "->" in line:
                    parts = line.split("->")
                    if len(parts) == 2:
                        invalid = parts[0].strip()
                        valid = parts[1].strip()
                        if invalid in invalid_icons and valid in valid_icons:
                            corrections[invalid] = valid

            return corrections

        except Exception as e:
            print(f"Error getting Lucide icon corrections: {e}")
            return {}

    def _ensure_complete_html_structure(self, html_content: str) -> str:
        """
        Ensure the HTML content has a proper head section for Mermaid.js script injection.
        This is necessary because Mermaid.js scripts must be loaded before the diagrams.

        Args:
            html_content: HTML content that may be missing head section

        Returns:
            Complete HTML with proper head section
        """
        # If already has proper head section, return as-is
        if "<head>" in html_content and "</head>" in html_content:
            return html_content

        # If it's a complete document but missing head, add one
        if "<!doctype html>" in html_content.lower() or "<html" in html_content.lower():
            # Find where to insert head section
            html_start = html_content.find("<html")
            if html_start != -1:
                html_tag_end = html_content.find(">", html_start) + 1
                # Insert head section right after <html>
                head_section = """
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.10.2/dist/full.min.css" rel="stylesheet" type="text/css" />
    <style>
        body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background-color: #ffffff;
        }
        .text-primary { color: #dc261e; }
        .bg-primary { background-color: #dc261e; }
        .border-primary { border-color: #dc261e; }
        .text-heading { color: #2d3748; }
        .text-body { color: #000000; }
    </style>
</head>"""
                return (
                    html_content[:html_tag_end]
                    + head_section
                    + html_content[html_tag_end:]
                )

        # If it's just body content, wrap it in complete HTML structure
        if "<body" in html_content or "<div" in html_content:
            return (
                html_content  # Assume it's already properly structured from generation
            )

        # Fallback: basic wrapper
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; margin: 20px; }}
        .text-primary {{ color: #dc261e; }}
    </style>
</head>
<body>
    {html_content}
</body>
</html>"""
